apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: sre-lab
  labels:
    app: jaeger
spec:
  type: ClusterIP
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: ui
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
