apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres/secret.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - jaeger/deployment.yaml
  - jaeger/service.yaml
  - checkout-service/configmap.yaml
  - checkout-service/secret.yaml
  - checkout-service/deployment.yaml
  - checkout-service/service.yaml
