apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - checkout-service/configmap.yaml
  - checkout-service/secret.yaml
  - checkout-service/deployment.yaml
  - checkout-service/service.yaml
