apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - postgres/secret.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - jaeger/deployment.yaml
  - jaeger/service.yaml
  - kube-state-metrics/serviceaccount.yaml
  - kube-state-metrics/rbac.yaml
  - kube-state-metrics/deployment.yaml
  - kube-state-metrics/service.yaml
  - prometheus/rbac.yaml
  - prometheus/configmap.yaml
  - prometheus/rules-configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  - grafana/secret.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - checkout-service/configmap.yaml
  - checkout-service/secret.yaml
  - checkout-service/deployment.yaml
  - checkout-service/service.yaml

configMapGenerator:
  - name: grafana-datasources
    namespace: sre-lab
    files:
      - prometheus.yml=grafana/provisioning/datasources/prometheus.yml
  - name: grafana-dashboard-providers
    namespace: sre-lab
    files:
      - dashboards.yml=grafana/provisioning/dashboards/dashboards.yml
  - name: grafana-dashboards
    namespace: sre-lab
    files:
      - checkout-latency.json=grafana/dashboards/checkout-latency.json
      - oomkilled.json=grafana/dashboards/oomkilled.json
